WCompass/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageView, CompanyDetailVIew, VacancyDetailView

app_name = "main"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('company/', CompanyDetailVIew.as_view(), name='company'),
    path('vacancy/', VacancyDetailView.as_view(), name='vacancy'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Locations(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='logos/', default=None)
    location = models.ManyToManyField(Locations)

    def __str__(self):
        return self.name

class VacancyType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class RequirementTech(models.Model):
    name = models.CharField(max_length=255)

class Vacancy(models.Model):
    name = models.CharField(max_length=255)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    start_date = models.DateTimeField(default=None, blank=True)
    detail = models.CharField(max_length=255)
    vacancy_type = models.ManyToManyField(VacancyType)
    requirement_tech = models.ManyToManyField(RequirementTech)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView
# Create your views here.

from .models import *

class HomePageView(ListView):
    model = Vacancy
    template_name = "index.html"
    context_object_name = "vacancy_list"
    
class CompanyDetailVIew(TemplateView):
    template_name = "educenter.html"

class VacancyDetailView(TemplateView):
    template_name = "vacancy-detail.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.4.2/css/all.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "./assets/css/style.css" %}">
    <title>Main | W.Corp</title>
</head>

{% block  content%}

{% endblock  %}



<script src="{% static "./assets/js/main.js" %}"></script>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    AOS.init();
</script>

</html>

templates/course-detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.4.2/css/all.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/css/style.css">
    <title>Vakansiya | Grafik dizayner kerak! | W.Corp</title>
</head>

<body>
    <header>
        <div class="section-wrapp">
            <div class="container educenter advanced">
                <img class="educenter-bg_img" src="./assets/img/places/najot te'lim.png" alt="">
                <div class="educenter-top">
                    <a href="/" class="general-back_link"><i class="fa-regular fa-angle-left"></i></a>
                    <img class="educenter-pfp-img" src="./assets/img/edu centers/najot talim.png" alt="">
                    <h1 class="educenter-name">Najot Ta'lim</h1>
                    <p class="educenter-location"><i class="fa-regular fa-location-dot"></i> Farg'ona - Toshkent</p>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="section-wrapp">
            <div class="container mid">
                <div class="course-heading_wrapper">
                    <h1 class="course-heading">O'quv markazi - Front-end</h1>
                    <span class="course-filter">
                        <i class="fa-solid fa-bars-sort"></i>
                    </span>
                </div>

                <div class="course-student_loop">
                    <div class="course-student_item">
                        <img src="" alt="">
                        <div class="course-student_info">
                            <div class="course-student_name"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
<script src="./assets/js/main.js"></script>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    AOS.init();
</script>

</html>

templates/educenter.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    
<body>
    <header>
        <div class="section-wrapp">
            <div class="container educenter advanced">
                <img class="educenter-bg_img" src="{% static "./assets/img/places/najot te'lim.png" %}" alt="">
                <div class="educenter-top">
                    <a href="/" class="general-back_link"><i class="fa-regular fa-angle-left"></i></a>
                    <img class="educenter-pfp-img" src="./assets/img/edu centers/najot talim.png" alt="">
                    <h1 class="educenter-name">Najot Ta'lim</h1>
                    <p class="educenter-location"><i class="fa-regular fa-location-dot"></i> Farg'ona - Toshkent</p>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="section-wrapp">
            <div class="container educenter mid">
                <div class="educenter-top_filter">
                    <div class="educenter-left educenter-side active">
                        O'quv kurslari
                    </div>
                    <div class="educenter-right educenter-side">
                        Vakansiyalar
                    </div>
                    <div class="educenter-line"></div>
                </div>
                <div class="educenter-course-loop side_loop">
                    <a href="/" class="educenter-course-item" data-aos="fade-up">
                        <img src="{% static "./assets/img/sam-user-pfp.png" %}" alt="">
                        <div class="educenter-course_info">
                            <p class="educenter-course_name">Front-End Developerlar</p>
                            <p class="educenter-course_quantity">O'quvchilar soni: 45</p>
                        </div>
                    </a>

                    <a href="/" class="educenter-course-item" data-aos="fade-up">
                        <img src="{% static "./assets/img/naz-user-pfp.png" %}" alt="">
                        <div class="educenter-course_info">
                            <p class="educenter-course_name">Back-End Developerlar</p>
                            <p class="educenter-course_quantity">O'quvchilar soni: 45</p>
                        </div>
                    </a>

                    <a href="/" class="educenter-course-item" data-aos="fade-up">
                        <img src="{% static "./assets/img/fes-user-pfp.png" %}" alt="">
                        <div class="educenter-course_info">
                            <p class="educenter-course_name">Dizaynerlar</p>
                            <p class="educenter-course_quantity">O'quvchilar soni: 45</p>
                        </div>
                    </a>

                    <a href="/" class="educenter-course-item" data-aos="fade-up">
                        <img src="{% static "./assets/img/rui-user-pfp.png" %}" alt="">
                        <div class="educenter-course_info">
                            <p class="educenter-course_name">Bot developerlar</p>
                            <p class="educenter-course_quantity">O'quvchilar soni: 45</p>
                        </div>
                    </a>
                </div>
                <div class="vacancies_loop side_loop closed-loop">
                    <div class="vacancies-item" data-aos="fade-up">
                        <div class="vacancy-item_right">
                            <img src="{% static "./assets/img/edu centers/najot talim.png" %}" alt="">
                        </div>
                        <div class="vacancy-item_left">
                            <h1 class="vacancy-company_name">Najot Ta'lim</h1>
                            <p class="vacancy-title vacancy-info">Python dasturchi kerak!</p>
                            <p class="vacancy-experience vacancy-info">Tajriba: 2 yil</p>
                            <p class="vacancy-age vacancy-info">Yoshi: 20+</p>
                            <p class="vacancy-tech vacancy-info">Texnologiyalar: Django,<a
                                    href="{% url "main:vacancy" %}">...</a></p>
                            <p class="vacancy-link vacancy-info"><a href="{% url "main:vacancy" %}">Ko'rish</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<body>
    <header>
        <div class="section-wrapp">
            <div class="container educenter">
                <div class="main-header_top_wrapper">
                    <div class="main-header_top-right">
                        <a href="/" class="main-logo">
                            <img src="{% static "./assets/img/logo.svg" %}" alt="">
                        </a>
                        <h1 class="main-request_username">Ilyosbek</h1>
                        <p class="main-current_location">
                            <i class="fa-regular fa-location-dot"></i>
                            <span class="main-current_id_location"></span>
                        </p>
                    </div>
                    <div class="main-header_top-left">
                        <img src="{% static "./assets/img/sam-user-pfp.png" %}" alt="">
                    </div>
                </div>

                <div class="main-header_top_block_wrapper">
                    <div class="main-header_top-search">
                        <form action="" class="main-search_form">
                            <input type="text" class="main-search_input" placeholder="Ish/Ishchi qidiring...">
                            <button type="submit" class="main-search_btn">
                                <i class="fa-regular fa-search"></i>
                            </button>
                        </form>
                    </div>
                    <div class="main-header_top-filter">
                        <i class="fa-solid fa-bars-sort"></i>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main>
        <div class="section-wrapp">
            <div class="container">
                <div class="main-edu_centers">
                    <div class="main-block_header">
                        <h1 class="main-block_heading">O’quv markazlar</h1>
                        <a href="/" class="main-block_link">
                            Hammasi
                        </a>
                    </div>
                    <div class="main-educenter-scroll">
                        <div class="main-educenter_loop">
                            <a href="{% url "main:company" %}" class="main-educenter-item">
                                <img src="{% static "./assets/img/edu centers/najot talim.png" %}" alt="">
                                <p class="main-educenter-item_name">Najot Ta'lim</p>
                                <span class="main-educenter-item_type">O'quv markazi</span>
                            </a>

                            <a href="{% url "main:company" %}" class="main-educenter-item">
                                <img src="{% static './assets/img/edu centers/mohirdev.png' %}" alt="">
                                <p class="main-educenter-item_name">MohirDev</p>
                                <span class="main-educenter-item_type">O’quv akademiya</span>
                            </a>

                            <a href="{% url "main:company" %}" class="main-educenter-item">
                                <img src="{% static './assets/img/edu centers/robocode.png' %}" alt="">
                                <p class="main-educenter-item_name">Robocode</p>
                                <span class="main-educenter-item_type">O'quv markazi</span>
                            </a>

                            <a href="{% url "main:company" %}" class="main-educenter-item">
                                <img src="{% static './assets/img/edu centers/astrum.png' %}" alt="">
                                <p class="main-educenter-item_name">Astrum</p>
                                <span class="main-educenter-item_type">O'quv akademiya</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="main-vacancies">
                    <div class="main-block_header">
                        <h1 class="main-block_heading">Vakansiyalar</h1>
                        <a href="/" class="main-block_link">
                            Hammasi
                        </a>
                    </div>

                    <div class="vacancies_loop">
                        {% for vacancy in vacancy_list %}
                        <div class="vacancies-item" data-aos="fade-up">
                            <div class="vacancy-item_right">
                                <img src="{{ vacancy.company.logo.url }}" alt="{{ vacancy.company.name }} logo">
                            </div>
                    
                            <div class="vacancy-item_left">
                                <h1 class="vacancy-company_name">{{ vacancy.company.name }}</h1>
                                <p class="vacancy-title vacancy-info">{{ vacancy.name }}</p>
                         
                                <p class="vacancy-experience vacancy-info">Tajriba: {{ vacancy.experience_years }} yil</p>
                                <p class="vacancy-age vacancy-info">Yoshi: {{ vacancy.minimum_age }}+</p>
                                <p class="vacancy-tech vacancy-info">
                                    Texnologiyalar: 
                                    {% for tech in vacancy.requirement_tech.all %}
                                        {{ tech.name }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </p>
                                <p class="vacancy-link vacancy-info"><a href="">Ko'rish</a></p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
{% endblock content %}

templates/starting.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>Starting | W.Corp</title>
</head>

<body>
    <header>
        <div class="section-wrapp">
            <div class="container">
                <div class="header-wrapp">
                    <a href="/" class="logo">
                        <img src="./assets/img/logo.svg" alt="">
                    </a>

                    <div class="login-img">
                        <img src="./assets/img/login-a.svg" alt="">
                        <p>Keling, biz bilan "A" ni topaylik</p>
                    </div>

                    <div class="login-auth">
                        <p class="login-auth_info">Biz bilan o’zingizga mos ish/hodim toping!</p>

                        <a href="./auth/login.html" class="login-auth_link_btn">Kirish</a>

                        <a href="./auth/register.html" class="login-auth_link">Royxatdan otish</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
</body>

</html>

templates/vacancy-detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<body>
    <header>
        <div class="section-wrapp">
            <div class="container educenter advanced">
                <img class="educenter-bg_img" src="{% static "./assets/img/places/najot te'lim.png" %}" alt="">
                <div class="educenter-top">
                    <a href="/" class="general-back_link"><i class="fa-regular fa-angle-left"></i></a>
                    <img class="educenter-pfp-img" src="./assets/img/edu centers/najot talim.png" alt="">
                    <h1 class="educenter-name">Najot Ta'lim</h1>
                    <p class="educenter-location"><i class="fa-regular fa-location-dot"></i> Farg'ona - Toshkent</p>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="section-wrapp">
            <div class="container mid">
                <h1 class="vacancy-heading">Vakansiya: <span>Python dasturchi</span></h1>
                <div class="vacancy-block">
                    <h1 class="vacancy-block_heading">Sizni kutadigan vazifalar</h1>
                    <p class="vacancy-block_info">
                        — Arxitekturani yaratish va mahsulot funksiyalarini ishlab chiqish. <br>
                        — Qimmatli texnik masalalarni o'rnating. <br>
                        — Asosiy texnik qarorlarni yana qabul qilish. <br>
                        — Tarmoq, ishlab chiqish asboblari va jismoniy ko'rinishlarni rivojlanish.
                    </p>
                </div>

                <div class="vacancy-block">
                    <h1 class="vacancy-block_heading">Biz sizdan kutmoqdamiz</h1>
                    <p class="vacancy-block_info">
                        — Python yoki Go da kommersiyaviy ishlash uchun uch yildan ortiq va yoki boshqa tillardan ularga
                        o'tkazib ketmoqchi bolsangiz. <br>
                        — Klassik algoritmlar va ma'lumotlar strukturasi bilasiz. <br>
                        — Tizimlarni dizayn qilishni bilasiz.
                    </p>
                </div>

                <div class="vacancy-block">
                    <h1 class="vacancy-block_heading">Biz sizdan kutmoqdamiz</h1>
                    <p class="vacancy-block_info">
                        — Yaxshi kompyuterlar: MacBook Pro, Dell na Windows yoki Linux operatsion tizimlari bilan
                        o'tkazib ketgan kuchli noutbuk yoki zarur resurslar bilan ajratilgan virtual mashina. <br>
                        — Katta hajmli DMS polisi: dantologiya, ko'zni tiklash, har haftalik tekshirish va kritik
                        mashg'ulotlar (onkologiya, dil bemorliklar) kasb haydovchi kursatkichlari bilan. <br>
                    </p>
                </div>

                <form action="" class="vacancy-form">
                    <button type="submit">Ariza jo'natish</button>
                </form>
            </div>
        </div>
    </main>
</body>
{% endblock content %}